# CONSENSUS REFINEMENT & READ SELECTION
INS_T=0.25				# threshold for insertion refinement
DEL_T=0.60				# threshold for deletion refinement
SKIP_E=1				# skip reference elongation
MIN_LEN=125
GRID_ON=1

# STAGES
MATCH_PROG="BLAT"
SORT_PROG="LABEL BLAT"
ALIGN_PROG="SAM BLAT"
ASSEM_PROG="SSW"

# SECONDARY ASSEMBLY
RESIDUAL_ASSEMBLY_FACTOR=400
MIN_RP_RESIDUAL=150
MIN_RC_RESIDUAL=150
DO_SECONDARY=1
