# HEADER
PARAM_FILE_NAME="FLU-secondary-iri"
PARAM_FILE_AUTHOR="D. Pattinson"
PARAM_FILE_VERSION="1.0"
PARAM_FILE_DATE="2022-04-08"

# Secondary assembly
RESIDUAL_ASSEMBLY_FACTOR=400
MIN_RP_RESIDUAL=150
MIN_RC_RESIDUAL=150
DO_SECONDARY=1
